"""phase9_drop_ratings_add_google_modules

Revision ID: 80813cf87882
Revises: e5f6a7b8c9d0
Create Date: 2026-03-11 17:15:26.732842

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "80813cf87882"
down_revision: Union[str, None] = "e5f6a7b8c9d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "training_modules",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column(
            "phase_type",
            sa.Enum("WARMUP", "MAIN", "GAME", "COOLDOWN", name="phasetype"),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_public", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "module_drills",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("module_id", sa.String(), nullable=False),
        sa.Column("drill_id", sa.String(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("duration_override", sa.Integer(), nullable=True),
        sa.Column("coach_notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["drill_id"], ["drills.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["module_id"], ["training_modules.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_index("ix_ratings_drill_id", table_name="ratings")
    op.drop_index("ix_ratings_user_id", table_name="ratings")
    op.drop_table("ratings")
    op.drop_index("ix_comments_drill_id", table_name="comments")
    op.drop_index("ix_comments_session_id", table_name="comments")
    op.drop_constraint("comments_user_id_fkey", "comments", type_="foreignkey")
    op.drop_constraint("comments_drill_id_fkey", "comments", type_="foreignkey")
    op.drop_constraint("comments_parent_id_fkey", "comments", type_="foreignkey")
    op.drop_constraint("comments_session_id_fkey", "comments", type_="foreignkey")
    op.create_foreign_key(None, "comments", "sessions", ["session_id"], ["id"])
    op.create_foreign_key(None, "comments", "users", ["user_id"], ["id"])
    op.create_foreign_key(None, "comments", "drills", ["drill_id"], ["id"])
    op.create_foreign_key(None, "comments", "comments", ["parent_id"], ["id"])
    op.add_column(
        "drill_sessions", sa.Column("phase_label", sa.String(length=50), nullable=True)
    )
    op.drop_index("ix_favourites_drill_id", table_name="favourites")
    op.drop_index("ix_favourites_session_id", table_name="favourites")
    op.drop_index("ix_favourites_user_id", table_name="favourites")
    op.drop_constraint("favourites_user_id_fkey", "favourites", type_="foreignkey")
    op.drop_constraint("favourites_drill_id_fkey", "favourites", type_="foreignkey")
    op.drop_constraint("favourites_session_id_fkey", "favourites", type_="foreignkey")
    op.create_foreign_key(None, "favourites", "users", ["user_id"], ["id"])
    op.create_foreign_key(None, "favourites", "sessions", ["session_id"], ["id"])
    op.create_foreign_key(None, "favourites", "drills", ["drill_id"], ["id"])
    op.drop_index("ix_follows_follower_id", table_name="follows")
    op.drop_index("ix_follows_following_id", table_name="follows")
    op.drop_constraint("follows_following_id_fkey", "follows", type_="foreignkey")
    op.drop_constraint("follows_follower_id_fkey", "follows", type_="foreignkey")
    op.create_foreign_key(None, "follows", "users", ["follower_id"], ["id"])
    op.create_foreign_key(None, "follows", "users", ["following_id"], ["id"])
    op.add_column("users", sa.Column("google_id", sa.String(), nullable=True))
    op.alter_column("users", "password_hash", existing_type=sa.VARCHAR(), nullable=True)
    op.create_unique_constraint(None, "users", ["google_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.alter_column(
        "users", "password_hash", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_column("users", "google_id")
    op.drop_constraint(None, "follows", type_="foreignkey")
    op.drop_constraint(None, "follows", type_="foreignkey")
    op.create_foreign_key(
        "follows_follower_id_fkey",
        "follows",
        "users",
        ["follower_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "follows_following_id_fkey",
        "follows",
        "users",
        ["following_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        "ix_follows_following_id", "follows", ["following_id"], unique=False
    )
    op.create_index("ix_follows_follower_id", "follows", ["follower_id"], unique=False)
    op.drop_constraint(None, "favourites", type_="foreignkey")
    op.drop_constraint(None, "favourites", type_="foreignkey")
    op.drop_constraint(None, "favourites", type_="foreignkey")
    op.create_foreign_key(
        "favourites_session_id_fkey",
        "favourites",
        "sessions",
        ["session_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "favourites_drill_id_fkey",
        "favourites",
        "drills",
        ["drill_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "favourites_user_id_fkey",
        "favourites",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index("ix_favourites_user_id", "favourites", ["user_id"], unique=False)
    op.create_index(
        "ix_favourites_session_id", "favourites", ["session_id"], unique=False
    )
    op.create_index("ix_favourites_drill_id", "favourites", ["drill_id"], unique=False)
    op.drop_column("drill_sessions", "phase_label")
    op.drop_constraint(None, "comments", type_="foreignkey")
    op.drop_constraint(None, "comments", type_="foreignkey")
    op.drop_constraint(None, "comments", type_="foreignkey")
    op.drop_constraint(None, "comments", type_="foreignkey")
    op.create_foreign_key(
        "comments_session_id_fkey",
        "comments",
        "sessions",
        ["session_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "comments_parent_id_fkey",
        "comments",
        "comments",
        ["parent_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "comments_drill_id_fkey",
        "comments",
        "drills",
        ["drill_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "comments_user_id_fkey",
        "comments",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index("ix_comments_session_id", "comments", ["session_id"], unique=False)
    op.create_index("ix_comments_drill_id", "comments", ["drill_id"], unique=False)
    op.create_table(
        "ratings",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("drill_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("score", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["drill_id"],
            ["drills.id"],
            name="ratings_drill_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="ratings_user_id_fkey", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="ratings_pkey"),
        sa.UniqueConstraint("user_id", "drill_id", name="uq_rating_user_drill"),
    )
    op.create_index("ix_ratings_user_id", "ratings", ["user_id"], unique=False)
    op.create_index("ix_ratings_drill_id", "ratings", ["drill_id"], unique=False)
    op.drop_table("module_drills")
    op.drop_table("training_modules")
    # ### end Alembic commands ###
