"""initial

Revision ID: a55656c41165
Revises: efb31acc54eb
Create Date: 2026-03-09 18:19:42.902862

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "a55656c41165"
down_revision: Union[str, None] = "efb31acc54eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
