"""initial

Revision ID: efb31acc54eb
Revises: 
Create Date: 2026-03-09 18:13:25.021767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efb31acc54eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('club', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('coaching_level', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('drills',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('num_players_min', sa.Integer(), nullable=True),
    sa.Column('num_players_max', sa.Integer(), nullable=True),
    sa.Column('equipment', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('skill_tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('age_range', sa.Enum('U12', 'U14', 'U16', 'U18', 'ADULTS', 'ALL', name='agerange'), nullable=True),
    sa.Column('skill_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'ELITE', name='skilllevel'), nullable=True),
    sa.Column('focus_area', sa.Enum('SERVING', 'RECEPTION', 'SETTING', 'ATTACK', 'BLOCK', 'DEFENSE', 'TACTICS', 'FITNESS', 'FUN', 'WARMUP', name='focusarea'), nullable=True),
    sa.Column('drawing_json', sa.JSON(), nullable=True),
    sa.Column('drawing_thumb_url', sa.String(), nullable=True),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('likes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('drill_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['drill_id'], ['drills.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    op.drop_table('drills')
    op.drop_table('users')
    # ### end Alembic commands ###
